language: java
jdk: openjdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_6d0100271ced_key -iv $encrypted_6d0100271ced_iv
    -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - echo -e "Host $DIST_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    file: build/libs/*.jar
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
      repo: xebialabs-community/xlr-ucd-plugin
  - provider: script
    skip_cleanup: true
    script: rsync --update -raz -i $TRAVIS_BUILD_DIR/build/libs/*.jar $DIST_USER@$DIST_HOST:$DIST_PATH/${TRAVIS_REPO_SLUG#*/}/
    on:
      all_branches: true
      tags: true
      repo: xebialabs-community/xlr-ucd-plugin
notifications:
  slack:
    secure: Firh/BKd1JowxB338mFoDnAxw1OkbOe0U6PVj72WrKhU+gLaXV+bbTrbQYGsbnJJnn3EYz/F9SLzbOIqkg7M6beJZJw3q6xHwo7bPUCe6iZTFK4+bo1nn/jvxmOcnP4UfCyJtwohCr7Sv3MPExhJUYBOYTCQqwN9aF7vd06eTi2qlaN/2Dgh/dgR2HQfngtRJEGR6JK+EoqkXkqiPFF2x3afCAMt5tIsxgUFjI5mbrQCnYLghUHz+4xqFPoPxkrnTEW5eDzJhpyIFQuEmeNhr4HdBSexRdBT0/MQrw0iOXMoBAEX+Th/iUJ7b5BhJ5hxOxw5bXVPDBGII7Htkl8eoVZAqIQwaZelj/Knuwa61MPkfzn8qOxNj+mZtyn/G2Z2tRlhUn3OjKozGRZ+vYA4E+/tnleTsmw+6iigjrk/arRhBN+d6szlTnXo+VKg7zKRJOzOdw2TgAjP9+zDrUf6fsTmSjG1s/GIkjDsZ8pPpvoEXhRPFwGUVOALxzat/J2p8JFEGFTrA7fJknnYFRdefFmoEhSKgnjLoIrfyX/+QZICF4SfmUISOWIbE7mJW7YWIlkRmi4CUNizRJUnGHlmEB8laKTWLNb/XD59eviUODED10j894DaFOSwxPktdxBcoNPxyFwAPtVOALgO+6ReRf5VN1t737fk/ChZJfSvK7Q=